name: docs
on:
  workflow_call:
    inputs:
      pip_args:
        required: true
        type: string
jobs:
  gh-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: python-deps-${{ inputs.pip_args }}
          path: .
      - run: |
          unzip venv.zip
      - run: |
          .venv/bin/python -m mkdocs gh-deploy -f docs/mkdocs.yml --force
